const plot = [
  {
    "name": "ไฮโดรโปรนิกส์ 1",
    "id": "46",
    "animation": 0,
    "value": "",
    "endAnchor": "top",
    "topicControl": "",
    "topicData" : "",
    "topicAlive" : "",
    "alive": "",
    "ph" : "",
    "ec": "",
    "flowRate":"",
    "waterTemperature":"",
    "waterLevel":"",
    "camera":"http://root:ismart12@192.168.31.10/cgi-bin/currentpic.cgi"
  },
  {
    "name": "ไฮโดรโปรนิกส์ 2",
    "id": "47",
    "animation": 0,
    "value": "",
    "endAnchor": "top",
    "topicControl": "",
    "topicData" : "",
    "topicAlive" : "",
    "alive": "",
    "ph" : "",
    "ec": "",
    "flowRate":"",
    "waterTemperature":"",
    "waterLevel":"",
    "camera":"http://root:ismart12@192.168.31.10/cgi-bin/currentpic.cgi"
  }, {
    "name": "ไฮโดรโปรนิกส์ 3",
    "id": "48",
    "animation": 0,
    "value": "",
    "endAnchor": "top",
    "topicControl": "",
    "topicData" : "",
    "topicAlive" : "",
    "alive": "",
    "ph" : "",
    "ec": "",
    "flowRate":"",
    "waterTemperature":"",
    "waterLevel":"",
    "camera":"http://root:ismart12@192.168.31.10/cgi-bin/currentpic.cgi"
  },
  // {
  //   "name": "ไฟแปลง 1",
  //   "id": "63",
  //   "animation": 0,
  //   "value": "",
  //   "endAnchor": "top",
  //   "topicControl": "",
  //   "topicData" : "",
  //   "topicAlive" : "",
  //   "alive": "",
  // },
  // {
  //   "name": "ไฟแปลง 2",
  //   "id": "64",
  //   "animation": 0,
  //   "value": "",
  //   "endAnchor": "top",
  //   "topicControl": "",
  //   "topicData" : "",
  //   "topicAlive" : "",
  //   "alive": "",
  // },
  // {
  //   "name": "ไฟแปลง 3",
  //   "id": "65",
  //   "animation": 0,
  //   "value": "",
  //   "endAnchor": "top",
  //   "topicControl": "",
  //   "topicData" : "",
  //   "topicAlive" : "",
  //   "alive": "",
  // },
]

module.exports = plot